#!/usr/bin/env node
var suffixes = ['ID', 'SECRET', 'REFRESH_TOKEN']
suffixes.forEach(function (suffix) {
  var name = 'GOOGLE_DRIVE_' + suffix
  if (!process.env[name]) {
    console.error('Missing ' + name)
    process.exit(1)
  }
})

var fs = require('fs')
var mappings = require('./google-drive.json')
var path = require('path')
var runParallel = require('run-parallel')
var update = require('update-google-drive-document')

runParallel(mappings.map(function (mapping) {
  return function (done) {
    update(
      process.env.GOOGLE_DRIVE_ID,
      process.env.GOOGLE_DRIVE_SECRET,
      process.env.GOOGLE_DRIVE_REFRESH_TOKEN,
      mapping.drive,
      fs.createReadStream(
        path.join(__dirname, 'build', mapping.id + '.docx')
      ),
      done
    )
  }
}), function (error) {
  if (error) {
    console.error(error)
    process.exit(1)
  } else {
    console.log('Updated ' + mappings.length + ' documents.')
  }
})
